### ISSUE TITLE
model connection object

### ISSUE THREAD

**Issue by ghost** [FrankieTh-xx/twobirds#1]
Hi,

it would be great to be able to switch between connection:
- define a connection object

{
  'production':'https://example.com/production',
  'testing':'https://example.com/testing',
}
- use a connection like:

Model.config.connect = 'testing'

**Comment by twoBirds** [comment]
Will do this... both on the class as well as inside the model instance. So e.g. you will be able to run parts of the software on mock level while the rest runs on real database connections. This will be configurable in general as well as ad-hoc in the code. I expect 2-3 days until its done.

**Comment by twoBirds** [comment]
Hi again,

having a closer look I misunderstood your issue. The solution to your problem should not be in the tB core code, since it is project specific.

Your problem can be solved easily using the window.location object.
